/* Generated by wayland-scanner 1.23.90 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"


static const struct wl_interface *custom_brightness_protocol_types[] = {
	NULL,
};

static const struct wl_message custom_brightness_requests[] = {
	{ "set_brightness", "f", custom_brightness_protocol_types + 0 },
};

WL_EXPORT const struct wl_interface custom_brightness_interface = {
	"custom_brightness", 1,
	1, custom_brightness_requests,
	0, NULL,
};

