/* Generated by wayland-scanner 1.23.90 */

#ifndef CUSTOM_BRIGHTNESS_PROTOCOL_SERVER_PROTOCOL_H
#define CUSTOM_BRIGHTNESS_PROTOCOL_SERVER_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-server.h"

#ifdef  __cplusplus
extern "C" {
#endif

struct wl_client;
struct wl_resource;

/**
 * @page page_custom_brightness_protocol The custom_brightness_protocol protocol
 * @section page_ifaces_custom_brightness_protocol Interfaces
 * - @subpage page_iface_custom_brightness - 
 */
struct custom_brightness;

#ifndef CUSTOM_BRIGHTNESS_INTERFACE
#define CUSTOM_BRIGHTNESS_INTERFACE
/**
 * @page page_iface_custom_brightness custom_brightness
 * @section page_iface_custom_brightness_api API
 * See @ref iface_custom_brightness.
 */
/**
 * @defgroup iface_custom_brightness The custom_brightness interface
 */
extern const struct wl_interface custom_brightness_interface;
#endif

/**
 * @ingroup iface_custom_brightness
 * @struct custom_brightness_interface
 */
struct custom_brightness_interface {
	/**
	 * @param value Brightness value between 0.0 and 1.0
	 */
	void (*set_brightness)(struct wl_client *client,
			       struct wl_resource *resource,
			       wl_fixed_t value);
};


/**
 * @ingroup iface_custom_brightness
 */
#define CUSTOM_BRIGHTNESS_SET_BRIGHTNESS_SINCE_VERSION 1

#ifdef  __cplusplus
}
#endif

#endif
